title: "ChatGPT-API x Node.jsでお手軽GPT環境構築"
summary: "ChatGPT-APIとNode.jsを使用して、ローカル環境にChatGPTの環境を手軽に構築できる本となっています。"
topics: ["ChatGPT", "Nodejs", "JavaScript", "API"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - introduction
  - end